name: Frontend Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the code
      - uses: actions/checkout@v2
    # Run Tests
      - name: Run Tests
        uses: actions/setup-node@v1
        with: 
          node-version: 14.x
      - run: |
          yarn
          yarn test --watchAll=false