# .github/workflows/prod-pipeline.yml
# This is a github action pipeline for production.
name: Production Deployment
on: 
  workflow_dispatch
# Jobs
jobs: 
  deploy-prod:
    name: Deploy To Production
    runs-on: ubuntu-latest
    env:
      region: us-west-2
      bucket: dtoki-1208-app.czerotest.com
    steps:
      - name: Download artifact from build step
        uses: actions/download-artifact@v1
        with:
          name: build-artifact
      # Configure Aws account for S3 Sync
      - name: Configure AWS credentials for S3 sync
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }}
      # Deploy to s3
      - name: Copy files to the test website with the AWS CLI
        run: |
          cd build-artifact
          aws s3 sync . s3://${{ env.bucket }}
      # Invalidate Cloudfront
      - name: Invalidate Cloudfront
        run: |
          export DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[?@=='${{ env.bucket }}']].Id | [0]" | tr -d '"')
          aws cloudfront create-invalidation --distribution-id ${DIST_ID} --paths "/*"

